### PR TITLE
Remove LRU cache

### PR DESCRIPTION
**Pull request by dzeckelev**
At the moment we do not need the cache.
I propose to remove unnecessary dependencies.

Please check if what you want to add to `go-lachesis` list meets [quality standards](https://github.com/Fantom-foundation/go-lachesis/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request.

**Please provide package links to:**

- github.com repo:
- godoc.org:
- goreportcard.com:
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `[cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fuser%2Frepository)`

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/Fantom-foundation/go-lachesis/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/Fantom-foundation/go-lachesis/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/Fantom-foundation/go-lachesis/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by Maxime2** [comment]
Can you please provide any justification to the statement we do not not need cache? 
My tests show reduction of cache size let alone setting it to zero significantly reduces tps number.

**Comment by dzeckelev** [comment]
@Maxime2 this is a bad pr. I did not implement the extrusion feature. Now I think that it will not bring benefit and close it. =(

**Comment by SamuelMarks** [comment]
Glad this is resolved.

**Comment by Maxime2** [comment]
@dzeckelev What are reasons you have considered before replacing Hashcorp's LRU cache?
Just to clarify if it's worth to reinvent the wheel. We might need a project specific cache eviction policies down the track, but it could be implemented ontop of LRU cache.

**Comment by dzeckelev** [comment]
I think we don't need cache. We have a database in memory. It is better to refactor this base and assign the functions of the cache to it. This request should have been the starting point for it.
Now it is hard to debug the application and and introduce new functionality. My goal now is to simplify the application. We can optimize bottlenecks in the future.

**Pull request closed without merging**
