### PR TITLE
Key gen command

### PR DESCRIPTION
**Pull request by integraloleg**
1. Generate a private pem key using `key` command.
2. Use a private pem key in `start` command with `--key` flag.

### CODE REVIEW

**Comment by SamuelMarks** [comment]
@integraloleg It would be a good idea to split up obviously separate, decoupled, and useful-to-other-projects functionality to different repositories, like I've done with [batch-ethkey](https://github.com/SamuelMarks/batch-ethkey)

**Comment by integraloleg** [comment]
This functionality is not yet useful-to-other-projects because unstable. I think we should return to this later.

**Comment by SamuelMarks** [comment]
@integraloleg I'm worried that we're doing that everytime. Soon I'll be advocating—once again—splitting this repository up into bite sized repos. Each with their own tests and publicly defined interfaces, so that they can evolve independently (as long as the maintain their interface).

Something ridiculously independent exposable in a subcommand like this PR is the perfect case study. What is created could then be a tested dependency of [batch-ethkey](https://github.com/SamuelMarks/batch-ethkey), which could then join the ecosystem of subcommands.

**Comment by SamuelMarks** [comment]
😓

**Comment by Maxime2** [comment]
Though I would disagree on splitting ontol smaller repos just because of splitting, - such split should carefully thought out beforehand. But there is no point to include auxiliary functionality into a single executable as that executable would reside in memory for a long run and we will just waste memory for the code implementing the functionality not used in the current run.

**Pull request merged**
