### PR TITLE
PoS poset

### PR DESCRIPTION
**Pull request by devintegral**
It is a implementation draft of Lachesis consensus algorithm.
There are no serious changes in existing packages, only new src/posposet package mostly. So, new src/posposet is introduced as solid initial PR. 

Strengths and goals:

- Lachesis consensus algorithm by Fantom Lab research;
- genesis with stakes instead of fixed peer list;
- Prof-of-Stake based weight of nodes makes possible to build decentralized trustless network;
- clean and readable code, dedicated types for hash, address, time etc;
- one Store implementation over any key-value DB;
- sync event processing for test and async processing for prod, no timeouts from now on;
- no multiple checks for the same event;
- ASCII-scheme parser and events naming for tests;
- human-readable hashes in logs so easy debug;

### CODE REVIEW

**Comment by Maxime2** [comment]
Despite this PR has a number of traits and improvements it is a way off lachesis prototype in development and better be held until the prototype is implemented.

The second question is that it looks more like an attempt to bring some code from ethereum project, which is just would be redundant in spite of lachesis prototype implementation.

**Comment by devintegral** [comment]
@Maxime2,
1) There is no Lachesis prototype before my PR, there is Swirlds actualy.
2) There is only Merkle Trie implementation from geth rebased on our hash size and serialization agreement (protobuf). Which better way do you suggest for balance storage?

**Comment by SamuelMarks** [comment]
@devintegral @Maxime2 We seem to be stepping on each other's toes too much.

How about a major architectural re-engineering? - https://github.com/Fantom-foundation/go-lachesis/issues/166

**Comment by Maxime2** [comment]
@devintegral This repo is go-lachesis, why swirlds is still implementing here? If there is a need to implement swirlds then it is better to do in go-swirlds repo (created / forked from this one) as it is a separate protocol and its development is going into conflict with lachesis development.

@SamuelMarks I am for architecture re-structuring, though I am still in haze of overall goals of the project, which is needed to split it on parts efficiently.

**Comment by devintegral** [comment]
@Maxime2, you have gotten my answer exactly backwards. The thing you call "lachesis prototype" (src/poset) is not Lachesis actually. It is a Swirlds consensus algorithm - see voting at src/poset/poset.go:Poset.DecideAtropos() for example. Vice versa, there is true Lachesis consensus algorithm in my PR - see consensus time selection at src/posposet/poset.go:Poset.hasAtropos() for example.
And there is no conflict between src/poset and src/posposet. They are independent, and both might be used by node in future.
Therefore, your subsequent conclusions ("better to do in go-swirlds repo", "going into conflict") are based on your misunderstanding.

**Comment by Maxime2** [comment]
@devintegral The thing I have called "lachesis prototype" is in development and not yet pushed into master. It was said in my first comment. So you just have no information to say if it's true lachesis or not.

The implementation in current master is a long running attempt to morph swirlds into lachesis and is rather closer to lachesis that swirlds. And it has a problem with consensus on 15+ nodes.

The prototype has been tested on 15, 25, 35, and 65 nodes and it comes to consensus.

As I see, your PR is more logically organised attempt to implement lachesis though staying within general architecture of babble (swirlds implementation). Have you tested your posposet on 15+ nodes?

BTW, your previous attempt to bring these changes in #155 has clearly stated posposet would replace poset as a next step, and that is clearly stated conflict.

**Comment by quan8** [comment]
@devintegral , @devintegral2 , @integraloleg As said earlier, it would it be good to email for internal discussions. For this PR, it is too big, and it should be split into small ones. Any change into this repos must be follow the rules and PR submitter must not be anonymous. Thanks.

**Comment by devintegral** [comment]
@Maxime2, do you reject this published code with only reason you have unpublished code in development stage? Really!?

**Comment by quan8** [comment]
@devintegral This PR will be considered only if it meets the requirement.

**Comment by devintegral** [comment]
@quan8, as I said you early, the package is completely new, i.e it does not change existing packages, it is not necessary to realize its influence on legacy. Would be better to understand it as a whole part. 
If we break it into working stages of creation, we will need to explain the stubs, bad layouts, etc. In this case, there will be even more questions than now.
We have been working on this project for several months but unfortunately didn't cooperate with you before. We would be glad to discuss with you the project in any convenient way so you will not consider us anonymous. 
Also what exact requirements do you mean?
Because we work as agreed early - make PRs and don't merge it in master before testing and approval.

**Comment by quan8** [comment]
@devintegral It would be good to email any discussions about this PR to related developers. Previous PR (rejected) mentioned that this PR attempted to replace the existing poset. But we don't understand the context behind. So yes, please email for internal discussions (to related dev team members). It is a huge PR, and so need thorough discussions. 

From public repos point of view, it's better to know who made the commit (PR submitter), and so who will be responsible to fix if there will be issues with the PR and even to roll back the commit if need be. Thanks.

**Comment by devintegral** [comment]
@quan8, we surely discussed all our tasks and PRs in advance and work only after approval. I'll be glad if you share with me other related dev team members who should know about plans and further development.
As an author of the PR I surely responsible for it and you can see that I always react to any comments and ready for the discussion.
But to know each other better and be on the same page, we can also discuss the project in slack.

**Comment by quan8** [comment]
@Maxime2  can you and @devintegral check in this PR for its enhancements? We can defer part of it if there is a conflict with work in progress.

**Comment by Maxime2** [comment]
Moved from #166 
----------------
@devintegral section 7.1 of https://swirlds.com/downloads/SWIRLDS-TR-2016-01.pdf is a generalisation of Swirlds. May I see your research document reflecting it into Lachesis, in particular, why PoS approach was reflected for voting but not for time calculation; and have you proved you have the same value of  MinMax here https://github.com/Fantom-foundation/go-lachesis/blob/7ce8564514e144c4aa6bf3d634e383c96d55e0d6/src/posposet/poset.go#L303 on every node independently on selection of nodes forming the stake ?


You perhaps not get PoS task correctly, because it has nothing against fixed peer list, it assumes that each peer is not equal, and nothing else. So it could be predefined fixed peer list with assigned weight to each peer. Moreover cited paper says the PoS system is the same as original if you set weight 1 to each peer.

It is clear the re-run in case of stake change gives the biggest impact on performance when PoS is implemented. Have you done any research on possibility to avoid it?

Obviously the PoS specification doesn't require poset reengineering. I would prefer to change peers for that task rather than poset.

**Comment by devintegral** [comment]
@Maxime, first of all this PR is not completely ready solution, just like `src/poset` is not completely ready too. It is a research of lachesis implementation way with great potential. So, the point of this PR is PoS-way presentation. Approve it if you understand PoS value, otherwise don't.

Nonetheless, I will answer your questions.

> Why PoS approach was reflected for voting but not for time calculation?

You right, it will be changed to stake majority.

> You perhaps not get PoS task correctly, because it has nothing against fixed peer list, it assumes that each peer is not equal, and nothing else.

I preferred to get PoS task as general as possible. It is easy to get fixed peer list from unfixed by blocking stake transfer. But it is impossible to get unfixed peer list from fixed-by-design.

> It is clear the re-run in case of stake change gives the biggest impact on performance when PoS is implemented. Have you done any research on possibility to avoid it?

I can increase frames gap before apply new stakes (`const X` at `poset.go:144`). It avoid the impact on performance.

> I would prefer to change peers for that task rather than poset.

You are free to do it. I prefer poset refactoring, see https://github.com/Fantom-foundation/go-lachesis/issues/166#issuecomment-477096433

**Comment by Maxime2** [comment]
> @Maxime2, first of all this PR is not completely ready solution, just like `src/poset` is not completely ready too. It is a research of lachesis implementation way with great potential. So, the point of this PR is PoS-way presentation. Approve it if you understand PoS value, otherwise don't.

@devintegral I think I understand the value of PoS, as well the extend it changes lachesis algorithm and the need to do additional research to ensure it remains correct with that enhancement. And I do not see such research have done neither for swirlds neither for lachesis.

What I do not understand is your reference to PoS as reasoning for poset refactoring. It is absolutely not required for PoS implementation and in fact is premature, as lachesis itself is in development and its architecture is changing as you might see.

> > You perhaps not get PoS task correctly, because it has nothing against fixed peer list, it assumes that each peer is not equal, and nothing else.
> 
> I preferred to get PoS task as general as possible. It is easy to get fixed peer list from unfixed by blocking stake transfer. But it is impossible to get unfixed peer list from fixed-by-design.

So it is your preference, not the inconsistency with PoS idea as you initially stated in #166.

> > I would prefer to change peers for that task rather than poset.
> 
> You are free to do it. I prefer poset refactoring, see [#166 (comment)](https://github.com/Fantom-foundation/go-lachesis/issues/166#issuecomment-477096433)

Adding PoS via peers is indeed a small change: https://github.com/Maxime2/lachesis/commit/7384a4b5fdda808491cbb56c2a40ad8b4944e99f

Again, refactoring would be welcomed at later stage when lachesis is working in general and is proven to be correct, but now it just wrecked havoc on algorithm development.

**Comment by devintegral** [comment]
>  And I do not see such research have done neither for swirlds neither for lachesis.

This PR is a first stage of the such research.

> It is absolutely not required for PoS implementation and in fact is premature, as lachesis itself is in development and its architecture is changing as you might see.

PoS is a future of lachesis. It would be better to keep PoS in mind as soon as possible, so why not now? It will provide more realistic architecture. And why do you refuse this PR as architecture proposal? Is there any agreement about teams who can make architecture proposal?

> Adding PoS via peers is indeed a small change: Maxime2@7384a4b

I'm sorry, but that is not a PoS.

> now it just wrecked havoc on algorithm development.

No, it provides more clean and clear code as base for algorithm development and test. That PR does not oblige anyone to work with, but gets option.

**Comment by Maxime2** [comment]
> > And I do not see such research have done neither for swirlds neither for lachesis.
> 
> This PR is a first stage of the such research.

Under research I mean something like https://github.com/Fantom-foundation/fantom-framework
This PR is an implementation of something, not a research.

> 
> I'm sorry, but that is not a PoS.

Please elaborate which part of section 7.1 in https://swirlds.com/downloads/SWIRLDS-TR-2016-01.pdf makes you so categorical?

**Comment by devintegral** [comment]
I said no PoS because there is no _proof_ of stake transfer in Maxime2/lachesis@7384a4b.
In terms of section 7.1. it is: `each existing member could be allowed to invite arbitrarily many new members to join, subject to the constraint that the inviter must split their stake with the invitee`.

**Pull request merged**
